# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gpufancnvgui.ui'
#
# Created: Mon Aug 28 11:24:49 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(496, 354)
        MainWindow.setFocusPolicy(QtCore.Qt.WheelFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Dapino-Summer-Blue-Fan.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(165, 77, 211, 24))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.fancontrolon = QtGui.QRadioButton(self.groupBox)
        self.fancontrolon.setGeometry(QtCore.QRect(160, 2, 51, 22))
        self.fancontrolon.setObjectName(_fromUtf8("fancontrolon"))
        self.fancontroloff = QtGui.QRadioButton(self.groupBox)
        self.fancontroloff.setGeometry(QtCore.QRect(100, 2, 61, 22))
        self.fancontroloff.setChecked(True)
        self.fancontroloff.setObjectName(_fromUtf8("fancontroloff"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(6, 4, 86, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.tempslide0 = QtGui.QSlider(self.centralwidget)
        self.tempslide0.setGeometry(QtCore.QRect(42, 134, 200, 21))
        self.tempslide0.setMaximum(100)
        self.tempslide0.setProperty("value", 0)
        self.tempslide0.setSliderPosition(0)
        self.tempslide0.setOrientation(QtCore.Qt.Horizontal)
        self.tempslide0.setTickPosition(QtGui.QSlider.TicksBelow)
        self.tempslide0.setObjectName(_fromUtf8("tempslide0"))
        self.temp0h = QtGui.QLabel(self.centralwidget)
        self.temp0h.setGeometry(QtCore.QRect(242, 134, 31, 17))
        self.temp0h.setAlignment(QtCore.Qt.AlignCenter)
        self.temp0h.setObjectName(_fromUtf8("temp0h"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(62, 104, 161, 21))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(342, 104, 101, 21))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.temp0l = QtGui.QLabel(self.centralwidget)
        self.temp0l.setGeometry(QtCore.QRect(12, 134, 21, 20))
        self.temp0l.setAlignment(QtCore.Qt.AlignCenter)
        self.temp0l.setObjectName(_fromUtf8("temp0l"))
        self.temp1l = QtGui.QLabel(self.centralwidget)
        self.temp1l.setGeometry(QtCore.QRect(12, 164, 21, 17))
        self.temp1l.setAlignment(QtCore.Qt.AlignCenter)
        self.temp1l.setObjectName(_fromUtf8("temp1l"))
        self.tempslide1 = QtGui.QSlider(self.centralwidget)
        self.tempslide1.setGeometry(QtCore.QRect(42, 164, 200, 21))
        self.tempslide1.setMinimum(0)
        self.tempslide1.setMaximum(100)
        self.tempslide1.setProperty("value", 0)
        self.tempslide1.setOrientation(QtCore.Qt.Horizontal)
        self.tempslide1.setTickPosition(QtGui.QSlider.TicksBelow)
        self.tempslide1.setObjectName(_fromUtf8("tempslide1"))
        self.temp1h = QtGui.QLabel(self.centralwidget)
        self.temp1h.setGeometry(QtCore.QRect(242, 164, 31, 17))
        self.temp1h.setAlignment(QtCore.Qt.AlignCenter)
        self.temp1h.setObjectName(_fromUtf8("temp1h"))
        self.temp2l = QtGui.QLabel(self.centralwidget)
        self.temp2l.setGeometry(QtCore.QRect(12, 194, 21, 17))
        self.temp2l.setAlignment(QtCore.Qt.AlignCenter)
        self.temp2l.setObjectName(_fromUtf8("temp2l"))
        self.tempslide2 = QtGui.QSlider(self.centralwidget)
        self.tempslide2.setGeometry(QtCore.QRect(42, 194, 200, 21))
        self.tempslide2.setMinimum(0)
        self.tempslide2.setMaximum(100)
        self.tempslide2.setProperty("value", 0)
        self.tempslide2.setOrientation(QtCore.Qt.Horizontal)
        self.tempslide2.setTickPosition(QtGui.QSlider.TicksBelow)
        self.tempslide2.setObjectName(_fromUtf8("tempslide2"))
        self.temp2h = QtGui.QLabel(self.centralwidget)
        self.temp2h.setGeometry(QtCore.QRect(242, 194, 31, 17))
        self.temp2h.setAlignment(QtCore.Qt.AlignCenter)
        self.temp2h.setObjectName(_fromUtf8("temp2h"))
        self.temp3l = QtGui.QLabel(self.centralwidget)
        self.temp3l.setGeometry(QtCore.QRect(12, 224, 21, 17))
        self.temp3l.setAlignment(QtCore.Qt.AlignCenter)
        self.temp3l.setObjectName(_fromUtf8("temp3l"))
        self.tempslide3 = QtGui.QSlider(self.centralwidget)
        self.tempslide3.setGeometry(QtCore.QRect(42, 224, 200, 21))
        self.tempslide3.setMinimum(0)
        self.tempslide3.setMaximum(100)
        self.tempslide3.setProperty("value", 0)
        self.tempslide3.setOrientation(QtCore.Qt.Horizontal)
        self.tempslide3.setTickPosition(QtGui.QSlider.TicksBelow)
        self.tempslide3.setObjectName(_fromUtf8("tempslide3"))
        self.temp3h = QtGui.QLabel(self.centralwidget)
        self.temp3h.setGeometry(QtCore.QRect(242, 224, 31, 17))
        self.temp3h.setAlignment(QtCore.Qt.AlignCenter)
        self.temp3h.setObjectName(_fromUtf8("temp3h"))
        self.temp4l = QtGui.QLabel(self.centralwidget)
        self.temp4l.setGeometry(QtCore.QRect(12, 254, 21, 17))
        self.temp4l.setAlignment(QtCore.Qt.AlignCenter)
        self.temp4l.setObjectName(_fromUtf8("temp4l"))
        self.tempslide4 = QtGui.QSlider(self.centralwidget)
        self.tempslide4.setEnabled(False)
        self.tempslide4.setGeometry(QtCore.QRect(42, 254, 200, 21))
        self.tempslide4.setMinimum(0)
        self.tempslide4.setMaximum(100)
        self.tempslide4.setProperty("value", 100)
        self.tempslide4.setSliderPosition(100)
        self.tempslide4.setOrientation(QtCore.Qt.Horizontal)
        self.tempslide4.setTickPosition(QtGui.QSlider.TicksBelow)
        self.tempslide4.setObjectName(_fromUtf8("tempslide4"))
        self.temp4h = QtGui.QLabel(self.centralwidget)
        self.temp4h.setGeometry(QtCore.QRect(242, 254, 31, 17))
        self.temp4h.setAlignment(QtCore.Qt.AlignCenter)
        self.temp4h.setObjectName(_fromUtf8("temp4h"))
        self.speedslide2 = QtGui.QSlider(self.centralwidget)
        self.speedslide2.setGeometry(QtCore.QRect(292, 194, 160, 21))
        self.speedslide2.setMaximum(100)
        self.speedslide2.setOrientation(QtCore.Qt.Horizontal)
        self.speedslide2.setTickPosition(QtGui.QSlider.TicksBelow)
        self.speedslide2.setObjectName(_fromUtf8("speedslide2"))
        self.speedslide4 = QtGui.QSlider(self.centralwidget)
        self.speedslide4.setGeometry(QtCore.QRect(292, 254, 160, 21))
        self.speedslide4.setMaximum(100)
        self.speedslide4.setOrientation(QtCore.Qt.Horizontal)
        self.speedslide4.setTickPosition(QtGui.QSlider.TicksBelow)
        self.speedslide4.setObjectName(_fromUtf8("speedslide4"))
        self.speed3 = QtGui.QLabel(self.centralwidget)
        self.speed3.setGeometry(QtCore.QRect(452, 224, 31, 17))
        self.speed3.setAlignment(QtCore.Qt.AlignCenter)
        self.speed3.setObjectName(_fromUtf8("speed3"))
        self.speedslide1 = QtGui.QSlider(self.centralwidget)
        self.speedslide1.setGeometry(QtCore.QRect(292, 164, 160, 21))
        self.speedslide1.setMaximum(100)
        self.speedslide1.setOrientation(QtCore.Qt.Horizontal)
        self.speedslide1.setTickPosition(QtGui.QSlider.TicksBelow)
        self.speedslide1.setObjectName(_fromUtf8("speedslide1"))
        self.speed4 = QtGui.QLabel(self.centralwidget)
        self.speed4.setGeometry(QtCore.QRect(452, 254, 31, 17))
        self.speed4.setAlignment(QtCore.Qt.AlignCenter)
        self.speed4.setObjectName(_fromUtf8("speed4"))
        self.speed1 = QtGui.QLabel(self.centralwidget)
        self.speed1.setGeometry(QtCore.QRect(452, 164, 31, 17))
        self.speed1.setAlignment(QtCore.Qt.AlignCenter)
        self.speed1.setObjectName(_fromUtf8("speed1"))
        self.speed2 = QtGui.QLabel(self.centralwidget)
        self.speed2.setGeometry(QtCore.QRect(452, 194, 31, 17))
        self.speed2.setAlignment(QtCore.Qt.AlignCenter)
        self.speed2.setObjectName(_fromUtf8("speed2"))
        self.speedslide3 = QtGui.QSlider(self.centralwidget)
        self.speedslide3.setGeometry(QtCore.QRect(292, 224, 160, 21))
        self.speedslide3.setMaximum(100)
        self.speedslide3.setOrientation(QtCore.Qt.Horizontal)
        self.speedslide3.setTickPosition(QtGui.QSlider.TicksBelow)
        self.speedslide3.setObjectName(_fromUtf8("speedslide3"))
        self.speedslide0 = QtGui.QSlider(self.centralwidget)
        self.speedslide0.setGeometry(QtCore.QRect(292, 134, 160, 21))
        self.speedslide0.setMaximum(100)
        self.speedslide0.setOrientation(QtCore.Qt.Horizontal)
        self.speedslide0.setTickPosition(QtGui.QSlider.TicksBelow)
        self.speedslide0.setObjectName(_fromUtf8("speedslide0"))
        self.speed0 = QtGui.QLabel(self.centralwidget)
        self.speed0.setGeometry(QtCore.QRect(452, 134, 31, 17))
        self.speed0.setAlignment(QtCore.Qt.AlignCenter)
        self.speed0.setObjectName(_fromUtf8("speed0"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(12, 114, 31, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(242, 114, 31, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.savesettings = QtGui.QPushButton(self.centralwidget)
        self.savesettings.setGeometry(QtCore.QRect(302, 286, 141, 27))
        self.savesettings.setObjectName(_fromUtf8("savesettings"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(22, 294, 151, 16))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(42, 314, 131, 16))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.currtemp = QtGui.QLabel(self.centralwidget)
        self.currtemp.setGeometry(QtCore.QRect(182, 294, 31, 17))
        self.currtemp.setAlignment(QtCore.Qt.AlignCenter)
        self.currtemp.setObjectName(_fromUtf8("currtemp"))
        self.currspeed = QtGui.QLabel(self.centralwidget)
        self.currspeed.setGeometry(QtCore.QRect(182, 314, 31, 17))
        self.currspeed.setAlignment(QtCore.Qt.AlignCenter)
        self.currspeed.setObjectName(_fromUtf8("currspeed"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(212, 314, 20, 20))
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(212, 294, 21, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.revertsettings = QtGui.QPushButton(self.centralwidget)
        self.revertsettings.setEnabled(True)
        self.revertsettings.setGeometry(QtCore.QRect(324, 316, 98, 27))
        self.revertsettings.setObjectName(_fromUtf8("revertsettings"))
        self.lblselgpu = QtGui.QLabel(self.centralwidget)
        self.lblselgpu.setGeometry(QtCore.QRect(212, 22, 95, 23))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.lblselgpu.setFont(font)
        self.lblselgpu.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lblselgpu.setObjectName(_fromUtf8("lblselgpu"))
        self.gpuselected = QtGui.QSpinBox(self.centralwidget)
        self.gpuselected.setGeometry(QtCore.QRect(229, 45, 61, 33))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setKerning(True)
        self.gpuselected.setFont(font)
        self.gpuselected.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.gpuselected.setFrame(False)
        self.gpuselected.setAlignment(QtCore.Qt.AlignCenter)
        self.gpuselected.setAccelerated(False)
        self.gpuselected.setMinimum(0)
        self.gpuselected.setMaximum(1)
        self.gpuselected.setProperty("value", 0)
        self.gpuselected.setObjectName(_fromUtf8("gpuselected"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(49, 7, 47, 23))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.totnvgpus = QtGui.QLabel(self.centralwidget)
        self.totnvgpus.setGeometry(QtCore.QRect(10, 32, 23, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.totnvgpus.setFont(font)
        self.totnvgpus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.totnvgpus.setObjectName(_fromUtf8("totnvgpus"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(38, 32, 85, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(372, 7, 111, 23))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(421, 30, 61, 23))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.ctrlinterval = QtGui.QSpinBox(self.centralwidget)
        self.ctrlinterval.setGeometry(QtCore.QRect(371, 29, 51, 25))
        self.ctrlinterval.setFrame(True)
        self.ctrlinterval.setAlignment(QtCore.Qt.AlignCenter)
        self.ctrlinterval.setAccelerated(True)
        self.ctrlinterval.setMinimum(1)
        self.ctrlinterval.setMaximum(120)
        self.ctrlinterval.setProperty("value", 10)
        self.ctrlinterval.setObjectName(_fromUtf8("ctrlinterval"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.tempslide0, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.temp0h.setNum)
        QtCore.QObject.connect(self.tempslide0, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.temp1l.setNum)
        QtCore.QObject.connect(self.tempslide1, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.temp1h.setNum)
        QtCore.QObject.connect(self.tempslide1, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.temp2l.setNum)
        QtCore.QObject.connect(self.tempslide2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.temp2h.setNum)
        QtCore.QObject.connect(self.tempslide2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.temp3l.setNum)
        QtCore.QObject.connect(self.tempslide3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.temp3h.setNum)
        QtCore.QObject.connect(self.tempslide3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.temp4l.setNum)
        QtCore.QObject.connect(self.tempslide4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.temp4h.setNum)
        QtCore.QObject.connect(self.speedslide0, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.speed0.setNum)
        QtCore.QObject.connect(self.speedslide1, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.speed1.setNum)
        QtCore.QObject.connect(self.speedslide2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.speed2.setNum)
        QtCore.QObject.connect(self.speedslide3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.speed3.setNum)
        QtCore.QObject.connect(self.speedslide4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.speed4.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Nvidia Fan Control", None))
        self.fancontrolon.setText(_translate("MainWindow", "On", None))
        self.fancontroloff.setText(_translate("MainWindow", "Off", None))
        self.label_12.setText(_translate("MainWindow", "Fan Control:", None))
        self.temp0h.setText(_translate("MainWindow", "0", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" text-decoration: underline;\">Temperature Range</span> (<span style=\" vertical-align:super;\">o</span>C)</p></body></html>", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" text-decoration: underline;\">Fan Speed</span> (%)</p></body></html>", None))
        self.temp0l.setText(_translate("MainWindow", "0", None))
        self.temp1l.setText(_translate("MainWindow", "0", None))
        self.temp1h.setText(_translate("MainWindow", "0", None))
        self.temp2l.setText(_translate("MainWindow", "0", None))
        self.temp2h.setText(_translate("MainWindow", "0", None))
        self.temp3l.setText(_translate("MainWindow", "0", None))
        self.temp3h.setText(_translate("MainWindow", "0", None))
        self.temp4l.setText(_translate("MainWindow", "0", None))
        self.temp4h.setText(_translate("MainWindow", "100+", None))
        self.speed3.setText(_translate("MainWindow", "0", None))
        self.speed4.setText(_translate("MainWindow", "0", None))
        self.speed1.setText(_translate("MainWindow", "0", None))
        self.speed2.setText(_translate("MainWindow", "0", None))
        self.speed0.setText(_translate("MainWindow", "0", None))
        self.label_3.setText(_translate("MainWindow", "Min", None))
        self.label_4.setText(_translate("MainWindow", "Max", None))
        self.savesettings.setText(_translate("MainWindow", "Save Settings", None))
        self.label_8.setText(_translate("MainWindow", "Current temperature:", None))
        self.label_9.setText(_translate("MainWindow", "Current fan speed:", None))
        self.currtemp.setText(_translate("MainWindow", "0", None))
        self.currspeed.setText(_translate("MainWindow", "0", None))
        self.label_10.setText(_translate("MainWindow", "%", None))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" vertical-align:super;\">o</span>C</p></body></html>", None))
        self.revertsettings.setText(_translate("MainWindow", "Revert", None))
        self.lblselgpu.setText(_translate("MainWindow", "Selected GPU", None))
        self.label_5.setText(_translate("MainWindow", "Found", None))
        self.totnvgpus.setText(_translate("MainWindow", "0", None))
        self.label_17.setText(_translate("MainWindow", "Nvidia GPUs", None))
        self.label_6.setText(_translate("MainWindow", "Control interval", None))
        self.label_7.setText(_translate("MainWindow", "seconds", None))

